package fr.dsirc.poc.jbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TestObject() {
    }

}