package fr.dsirc.poc.jbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "lastnameLabel")
   private java.lang.String lastnameId;

   public TestObject()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getLastnameId()
   {
      return this.lastnameId;
   }

   public void setLastnameId(java.lang.String lastnameId)
   {
      this.lastnameId = lastnameId;
   }

   public TestObject(java.lang.String name, java.lang.String lastnameId)
   {
      this.name = name;
      this.lastnameId = lastnameId;
   }

}